
FROM node:16.4.2-alpine3.11 AS builder
WORKDIR /app 
COPY . . 

RUN npm
RUN npm run build 

FROM node:16.4.2-alpine3.11 
WORKDIR /usr/src/app 
COPY --from=builder /app ./ 

EXPOSE 25000 
CMD npm run start:prod
